sudo: required
dist: trusty

language: c

compiler:
  - clang
  - gcc-4.9
  
addons:
  apt:
    packages:
    - cmake
    - libopenblas-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .


